### ISSUE TITLE
[improvement]: enable node-package updates

### ISSUE THREAD

**Issue by hknet** [FreePBX/sng_freepbx_debian_install#139]
### FreePBX Version

FreePBX 17

### Improvement Description

The freepbx debian install basically puts all node-* packages on hold.
While I get the rationale behind having a stable nodejs framework, the fact that those packages and their respective udpates are coming from debian repos should probably allow for some security-updates like currently availabe:

`node-es-module-lexer/stable,stable 1.1.0+dfsg-2+deb12u1 all [upgradable from: 1.1.0+dfsg-2]`
`node-globby/stable,stable 13.1.3+~cs16.25.40-1+deb12u1 all [upgradable from: 13.1.3+~cs16.25.40-1]`
`node-tap/stable,stable 16.3.2+ds1+~cs50.8.16-1+deb12u1 all [upgradable from: 16.3.2+ds1+~cs50.8.16-1]`

So on one hand I'd be glad to know if there would be a consensus to update those packages and on the other hand it would be great if holding so many packages during a single point in time (setup of fp17) could be revisited as an issue for future updates of those packages.

**Comment by kguptasangoma** [comment]
Hi @hknet I can understand that due to security concerns we should have updated nodejs but Freepbx may not be compatible with the new nodejs hence we have to hold that package to ensure that system is always running compatible nodejs.

thanks

**Comment by JoseGoncalves** [comment]
Hi. I second @hknet request. Due to strict update policies in Debian stable releases, a package can only be updated to fix security or critical bug fixes. Being so, it's pefectly safe to unhold Node.js packages (and I've done it in my production system). The only way that I can see a Node.js package update to break things in FreePBX would be if it was upgraded to a different major version (i.e., from v18 to v19 or v20, for example), and that will never occur during the life of Debian 12.

**Comment by kguptasangoma** [comment]
Hi @JoseGoncalves 
Without testing we can not be sure that upgrading minor nodejs version may affect freepbx or not.
imagine you have up and running production system and then minor auto update happen due to any security fixes which may have impact on freepbx then all of sudden that will affect production system.

if its worth to take risk then user can manually unhold the package but node being critical dependent component for the freepbx , allowing auto upgrade is bit risky.  

We are not holding php 8.2.x due to the same reason as you said, minor package update will not break. may be over the period of time as Freepbx 17 become more stable we can revisit the same and remove the holding of nodejs packages.

**Comment by JoseGoncalves** [comment]
Hi @kguptasangoma. OK, I understand your point. Nevertheless, I assume the "risk" of unholding Node.js packages in my system because, being a Debian user for more than 20 years, I'm pretty confident that the possibility of a Debian stable package update to break anything on my system is very, very low. Moreover, I never make auto-upgrades in a production system, I always make my Debian package updates and FreePBX modules updates manually on weekends or at night, to be sure that I can recover from some failure without affecting my PBX users.
